sudo: required

language: java

services:
  - docker

script:
  - mvn clean install -Ddocker.useColor=false -Ddocker.showLogs -Pdocker -Pjacoco coveralls:report
  - version=$(printf 'VER\t${project.version}' | mvn help:evaluate | grep '^VER' | cut -f2)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag worker:${version} servicecomb/worker:${version}
  - docker push servicecomb/worker:${version}
  - docker tag beekeeper:${version} servicecomb/beekeeper:${version}
  - docker push servicecomb/beekeeper:${version}
  - docker tag doorman:${version} servicecomb/doorman:${version}
  - docker push servicecomb/doorman:${version}
  - docker tag manager:${version} servicecomb/manager:${version}
  - docker push servicecomb/manager:${version}
