apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: company-beekeeper
  name: company-beekeeper
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: company-beekeeper
    spec:
      containers:
      - env:
        - name: ARTIFACT_ID
          value: beekeeper
        - name: JAVA_OPTS
          value: -Dcse.service.registry.address=http://company-bulletin-board:30100 -Dservicecomb.tracing.collector.adress=http://zipkin:9411
        image: ericlee/beekeeper:0.0.1-SNAPSHOT
        name: company-beekeeper
        ports:
        - containerPort: 8090
        resources: {}
      restartPolicy: Always
status: {}
