apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: company-bulletin-board
  name: company-bulletin-board
spec:
  ports:
  - name: "30100"
    port: 30100
    targetPort: 30100
  selector:
    io.kompose.service: company-bulletin-board
status:
  loadBalancer: {}
